/* 
 * Zach Schulze
 * 7/23/2014
 * 
 * Project Euler
 * Problem 2
 * Even Fibonacci numbers
 *
 * Each new term in the Fibonacci sequence is generated by adding the previous
 * two terms. By starting with 1 and 2, the first 10 terms will be:
 * 1,2,3,5,8,13,21,34,55,89,...
 * 
 * By considering the terms in the Fibonacci sequence whose values do not
 * exceed four million, find the sum of the even-valued terms.
 */

public class p002 {
	public static void main(String[] args) {
		int x = 0;
		int y = 1;
		int tmp = 0;
		int sum = 0;
		
		while (tmp < 4000000)
		{
			tmp = x + y;
			x = y;
			y = tmp;
			System.out.println("tmp " + tmp);
			if (tmp % 2 == 0)
			{
				sum += tmp;
				System.out.println("sum " + sum);
			}
		}
		
		System.out.println("Sum of even-valued Fibonacci numbers up to four "
				+ "million: " + sum);
	}
}
